version: "3.9"

services:

  publisher:
    container_name: publisher
    hostname: publisher
    ports:
      - 5000:8080
    build:
      context: .
      dockerfile: ./Publisher/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis

  subscriber:
    container_name: subscriber
    hostname: subscriber
    build:
      context: .
      dockerfile: ./Subscriber/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - redis

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - '6379:6379'
      